apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: echo
      image: golang:1.17-alpine
      command:
        - echo
      args:
        - "Hello World"
    - name: run-test
      image: golang:1.17-alpine
      workingDir: /workspace/repo/src
      command: ["go"]
      args: ["test"]
